
variables:
  VERSION: "0.0-Alpha-Dev"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - lint
  - test
  # - deploy

base:
  stage: build
  image: docker-private-snapshots.gesis.intra/gesis/dc:50-extend-base-image-for-python-usage
  script:
    - ls

PyLint:
  stage: lint
  extends: base
  script:
    - /python/venv/bin/python -m pylint ./src

Ensure Pep8:
  stage: lint
  extends: base
  script:
    - /python/venv/bin/python -m flake8 ./ 

Test:
  stage: test
  extends: base
  script:
    - /python/venv/bin/python -m coverage run -m pytest ./tests
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    reports:
      cobertura: coverage.xml

Typecheck:
  stage: test
  image: docker-private.gesis.intra/gesis/dc:42-install-npm
  before_script:
    - npm i -g pyright
    - npm i -g pyright-to-gitlab-ci
  script:
   - pyright ./src --outputjson > report_raw.json
   - pyright-to-gitlab-ci --src report_raw.json --output report.json --base_path .
  artifacts:
    paths:
      - report.json
    reports:
      codequality: report.json

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production

