variables:
  VERSION: "0.1-Beta-Dev"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - Build
  - Lint
  - Test
  - Sonarqube
  - Deploy
  - Badges

Base:
  stage: Build
  image: docker-private.gesis.intra/gesis/dc-python:1.0
  script:
    - echo "Installing package on base image, including development packages (pytest, flake8, etc.)"
    - /python/venv/bin/python -m poetry install --with dev

Ruff:
  stage: Lint
  extends: Base
  needs:
    - Base
  script:
    - echo "Running Ruff"
    - pip3 install ruff
    - ruff check


Pytest and Coverage:
  stage: Test
  extends: Base
  needs:
    - Ruff
  script:
    - echo "Running Coverage with Pytest"
    - /python/venv/bin/python -m poetry run coverage run -m pytest ./tests
    - echo "Uploading Coverage report to Gitlab"
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    paths:
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

Bandit:
  stage: Test
  extends: Base
  needs:
    - Ruff
  script:
    - echo "Running Bandit"
    - /python/venv/bin/python -m bandit -c pyproject.toml -r ./src/ --format txt > bandit.txt
    - echo "Uploading Coverage report to Gitlab"
  artifacts:
    paths:
      - bandit.txt
    reports:
      sast: bandit.txt

Typecheck:
  stage: Test
  needs:
    - Ruff
  image: docker-private.gesis.intra/gesis/dc-nodejs:1.0
  before_script:
    - npm i -g pyright
    - npm i -g pyright-to-gitlab-ci
  script:
    - echo "Running Pyright"
    - pyright ./src --outputjson > report_raw.json
    - echo "Uploading output to Gitlab as artifact"
    - pyright-to-gitlab-ci --src report_raw.json --output report.json --base_path .
  artifacts:
    paths:
      - report.json
    reports:
      codequality: report.json

Deploy to Test Server:
  stage: Deploy
  extends: Base
  when: manual
  script: echo "Use this to deploy your project to a test server"

Deploy to Production Server:
  stage: Deploy
  needs:
    - Pytest and Coverage
    - Typecheck
  environment: production
  when: manual
  script: echo "Define your deployment script!"

Publish Package to Gitlab Registry:
  stage: Deploy
  extends: Base
  when: manual
  script:
    - echo "This is the publishing stage"
    - /python/venv/bin/python -m poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - echo "Repository gitlab configured ..."
    - /python/venv/bin/python -m poetry build
    - echo "Build done ..."
    - /python/venv/bin/python -m poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}
    - echo "Publishing done!"

generate-badges:
  stage: Build
  image: docker-private.gesis.intra/gesis/dc-python:1.0
  when: manual
  script:
    - echo "Installing anybadge"
    - /python/venv/bin/python -m pip install anybadge
    - echo "Creating output directory"
    - mkdir ./badges/
    - echo "Generating badges"
    - /python/venv/bin/python generate_badges.py
    - echo "Uploading badges to Gitlab"
  artifacts:
    paths:
      - ./badges/python_version.svg
      - ./badges/pre_commit_version.svg
      - ./badges/poetry_version.svg
      - ./badges/python_runner_image.svg
