variables:
  VERSION: "0.1-Beta-Dev"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - Build
  - Lint
  - Test
  - Sonarqube
  - Deploy
  - Badges

Base:
  stage: Build
  image: docker-private.gesis.intra/gesis/dc-python:1-migrate-to-ruff
  script:
    - echo "Installing package on base image, including development packages"
    - /python/venv/bin/python -m poetry install --with dev
    - source /builds/omino/OpenResearchConverter/.venv/bin/activate

Lint:
  stage: Lint
  extends: Base
  needs:
    - Base
  script:
    - echo "Running Ruff's Linter"
    - /python/venv/bin/python -m ruff check ./src

Pytest and Coverage:
  stage: Test
  extends: Base
  needs:
    - Lint
  script:
    - echo "Running Coverage with Pytest"
    - /python/venv/bin/python -m poetry install --with dev
    - /python/venv/bin/python -m poetry run coverage run -m pytest ./tests
    - echo "Uploading Coverage report to Gitlab"
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    paths:
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

Bandit:
  stage: Test
  extends: Base
  needs:
    - Lint
  script:
    - echo "Running Bandit"
    - /python/venv/bin/python -m bandit -c pyproject.toml -r ./src/ --format txt > bandit.txt
    - echo "Uploading Coverage report to Gitlab"
  artifacts:
    paths:
      - bandit.txt
    reports:
      sast: bandit.txt

# Typecheck:
#   stage: Test
#   needs:
#     - Lint
#   image: docker-private.gesis.intra/gesis/dc-nodejs:1.0
#   before_script:
#     - npm i -g pyright
#     - npm i -g pyright-to-gitlab-ci
#     - make install_pyright
#     - echo "Activating Poetry virtual environment"
#     - source .venv/bin/activate
#   script:
#     - echo "Running Pyright"
#     - pyright ./src --outputjson > report_raw.json
#   after_script:
#     - echo "Uploading output to Gitlab as artifact"
#     - pyright-to-gitlab-ci --src report_raw.json --output report.json --base_path .
#     - python -m json.tool report.json
#   artifacts:
#     paths:
#       - report.json
#     reports:
#       codequality: report.json
#     expire_in: 1 week

Deploy to Production Server:
  stage: Deploy
  image: alpine:latest
  environment: production
  needs:
    - Pytest and Coverage
    - Bandit
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh openssl)'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY_ORC_DEMO" | tr -d '\r' > private.key.enc
  - openssl enc -d -a -A -in private.key.enc -out private.key
  - echo "" >> private.key
  - chmod 400 private.key
  - ssh-add private.key
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $ORC_DEMO_IP_ADDRESS >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh $SSH_USER@$ORC_DEMO_IP_ADDRESS "cd /orc/OpenResearchConverter; bash .update.sh; docker-compose down; docker-compose up --build -d"
  after_script:
  - rm private.key.enc private.key
  only:
  - dev

generate-badges:
  stage: Build
  image: docker-private.gesis.intra/gesis/dc-python:1.0
  only:
    - main
    - dev
  script:
    - echo "Installing anybadge"
    - /python/venv/bin/python -m pip install anybadge
    - echo "Creating output directory"
    - mkdir ./badges/
    - echo "Generating badges"
    - /python/venv/bin/python generate_badges.py
    - echo "Uploading badges to Gitlab"
  artifacts:
    paths:
      - ./badges/python_version.svg
      - ./badges/pre_commit_version.svg
      - ./badges/poetry_version.svg
      - ./badges/python_runner_image.svg
