services:
  nginx:
    container_name: reverse-proxy
    hostname: reverse
    image: nginx:latest
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_data:/etc/nginx
      - nginx_data:/etc/ssl/private
    restart: always
  #   networks:
  #     - frontend

  frontend:
    container_name: orc-frontend
    hostname: frontend
    build:
      context: ./src/orc/frontend/
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    # networks:
    #   - frontend
    #   - backend

  backend:
    container_name: orc-backend
    hostname: backend
    build:
      context: ./
      dockerfile: ./src/orc/backend/Dockerfile
    ports:
      - "8002:8002"
    # networks:
    #   - backend

volumes:
  nginx_data:
    {}
    # networks:
    #   frontend:
    #   backend:
