version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./src/orc/frontend/html:/usr/share/nginx/html
    restart: always

  demo_service:
    build:
      context: ./
      dockerfile: ./src/py_project_template.Dockerfile
      environment: ./src/environment/py_project_template.env

# Please note that currently this will not run from inside the dev container.
